title: 안녕
email: me@annyeong.me
description: >- # this means to ignore newlines until "baseurl:"
  배운 것들을 하나씩 정리합니다.
baseurl: ""
url: https://annyeong.me

author: An Nyeong

permalink: /:categories/:title

plugins:
  - jekyll-feed

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
