title: 안녕
email: me@annyeong.me
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: https://annyeong.me

author:
  twitter: compiztab
  github: nyeong

permalink: /:categories/:title

plugins:
  - jekyll-feed

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
